### PR TITLE
Added additional parameter to configure social sharing icons above and under posts

### PR DESCRIPTION
**Pull request by stoeps13**
Added param **socialsharing** to enable and disable socialsharing icons.

### CODE REVIEW

**Comment by appernetic** [comment]
On vacation, but checking it out just now!

You have an error in search-index.md

Building sites … ERROR 2018/07/20 13:14:41 failed to parse page metadata for "search-index.md": Near line 2 (last key parsed ''): bare keys cannot contain ':' for search-index.md

Replace ulr: with url =

**Comment by appernetic** [comment]
How do you activate search? Any search form on the site?

I don't think that sidebar social icons have been fully implemented. Ok found the showSocialInSidebar, but the flattr icon is not visible.. https://screenshots.firefox.com/eYhU0pvgWwcQslCc/localhost

**Comment by appernetic** [comment]
I thougt that I had read that Hugo has in memory indexing for search, but i can't find it in gohugo docs. 

What is bmc and ko-fi?

**Comment by appernetic** [comment]
I tested the search with the npm package hugo-lunr and created a lunr.json file. https://gohugo.io/tools/search/#readout

If you have url in search-index.md and not type = page it will not be created.

I removed url and added this to the file:
´´´
draft = false
type = "page"
´´´
then I can view it in the browser.

I don't understand the purpose of this file. I think it's better to have a lunr.js script and a search box somewhere.

**Comment by appernetic** [comment]
I found the  showSearchInSidebar = true

The search-index.md file creates a index.json that contains the index.html file not the lunr json content.

I removed the search-index.md and run npm run index which generated the lunr.json in /public. Then I renamed it to index.json.

This is the result:
https://screenshots.firefox.com/xqL9y9pBSE5cCJHh/localhost

Something strange going on..

**Comment by stoeps13** [comment]
I worked a little on the stuff after sending the pull request.

For search some stuff in config.toml needs set to generate json.

The box should show the search hits.

Let me finish the stuff and create documentation, hope I'm finished after your vacation.

**Comment by stoeps13** [comment]
Javascript for search only works with lunrjs 1.0 in the moment. On later versions I get errors in browser console. So npm could be the problem here.

Ko-fi is buy me a coffee site at ko-fi.com

Haven't tested flattr. Is there a flattr.html file somewhere? 

I'm on vacation too, no idea when I can add documentation.

**Comment by appernetic** [comment]
When I forked the theme, flattr or any other social icons in the sidebar was not fully implemented.

**Comment by appernetic** [comment]
Your lunr.js error in the later version could be because the index.json contains the wrong content.

**Comment by stoeps13** [comment]
I use the theme on stoeps.de and search works.

**Comment by stoeps13** [comment]
The social icons I use are implemented, not sure about flattr in the moment.

**Comment by appernetic** [comment]
I checked your site and your json file is a bit different. You have ref instead of uri. 

I tried to change the uri to ref in index.json and it worked.

https://screenshots.firefox.com/Cm3odttxzNftXBnY/localhost

You should change the name of the json to lunr.json in the js script. Then it will not be overwritten and you only have to add the search flag in config:

If you not have lunr:

npm init

npm install hugo-lunr

Add to package json in the script section:

 "index": "hugo-lunr"

Then run:

Hugo

npm run index

Then you can check the result: 

cd /public

python -m SimpleHTTPServer 8000

 And also remove the search-index.md file ..

**Comment by appernetic** [comment]
It's probably better to change the js code to uri instead of ref, because the hugo-lunr script generates the josn with uri by default.

**Comment by stoeps13** [comment]
No changes needed! Or do you mean for lunrjs > 2.0?

Here the way I use it:

## Added lunrjs search

Add to config.toml:

    [outputs]
      home = [ "HTML", "RSS", "JSON" ]
      post = [ "HTML" ]

    [params]
      showSearchInSidebar = true 

Create `search-index.md` in your content folder. 

    ---
    date: 2016-07-15T13:55:09+02:00
    type: "json"
    url: "index.json"
    ----

Output of JSON is generated from `layouts/json/single.html`.

Now Hugo generates the `index.json` file used with your page. So no npm needed or something else.

**Comment by appernetic** [comment]
Hm, it could be that I have installed lunr 2.0 and the js script is 1.0.

**Comment by appernetic** [comment]
Ok, so you don't have to run lunr with npm?

**Comment by stoeps13** [comment]
Nope, npm is not necessary. 

Just add the code above and hugo does the index generation.

**Comment by appernetic** [comment]
But you have to install lunr localy?

**Comment by appernetic** [comment]
Probably some documentation missing on gohugo about search.

**Comment by stoeps13** [comment]
No. Lunr is integrated through CDN in `layouts/partials/base/imports.html`

**Comment by appernetic** [comment]
I mean for building the lunr.json file. There is nothing in the gohugo docs that indicates that Hugo builds a search index only that you can install lunr and generate a json.  I have read about it somewhere else but can't remeber where.

**Comment by stoeps13** [comment]
I read first of it here:

https://discourse.gohugo.io/t/search-index-json-file-for-lunr-js/6286/23

And one of the links showed most of the JS Code. I justed added the link a href= and repaired some typos.

I like the way Hugo builds the index, don't wanna have npm or other requirements on top.
Working on migrating to lunr 2.3...

**Comment by appernetic** [comment]
I also added:

 [outputs]
  home = [ "HTML", "RSS", "JSON" ]
  post = [ "HTML" ]

And put back the search-index.md. And it will build a index.json containing the html code for the index.html. Strange. I am using v0.44

**Comment by stoeps13** [comment]
I use 0.42.2, I had the html code in index.json too, but I thought it changed after adding the outputs section. I update to 0.44, give me some minutes to double check.

Do you have layouts/json/single.html in your theme folder?

**Comment by appernetic** [comment]
Just checking

**Comment by appernetic** [comment]
Yes:

```
{{- $.Scratch.Add "index" slice -}} 
{{- range where .Site.Pages "Type" "not in" (slice "page" "json") -}} 
{{- $.Scratch.Add "index" (dict "title" .Title "ref" .Permalink "tags" .Params.tags "content" .Plain) -}} 
{{- end -}} {{- $.Scratch.Get "index" | jsonify -}} 
```

**Comment by stoeps13** [comment]
I just used this https://discourse.gohugo.io/t/search-index-json-file-for-lunr-js/6286/7

**Comment by stoeps13** [comment]
I updated to 0.44 and get a index.json with real json content.

**Comment by appernetic** [comment]
Fix the search-index.md add info in the README and I will merge this PR. Maybe it works for most of the users. Could be some Hugo glitch on Ubuntu 16.04 maybe.

**Comment by stoeps13** [comment]
I replaced a lot now and I'm not sure if my changes fit for everyone. So ignore my pull request please.

**Comment by appernetic** [comment]
Ok! Nice work anyway. I will checkout your repo at a later time!

**Pull request closed without merging**
