### PR TITLE
concat and minify js & css

### PR DESCRIPTION
**Pull request by raghur**
Uses hugo asset pipeline to bundle and minify js and css

Requires Hugo 0.43+

### CODE REVIEW

**Comment by raghur** [comment]
### BEFORE
2018-07-26 17_26_13-pagespeed insights _ https___developers google com_ - firefox nightly
2018-07-26 17_25_57-pagespeed insights _ https___developers google com_ - firefox nightly

### AFTER
image
image

**Comment by appernetic** [comment]
Nice work, merging!

**Comment by raghur** [comment]
@appernetic  you might want to do the same thing with mathjax etc that are pulled in from CDN. I don't use/know about mathjax stuff so have left it alone.

**Comment by appernetic** [comment]
How do you configure so it will not brake the site? I tried to use the exampleSite and got this error:  function "resources" not defined

**Comment by appernetic** [comment]
Tried with assetDir = "/" in config.toml and it did not work.

**Comment by raghur** [comment]
What's the version of hugo? piplines requires a recent hugo build (0.43+) I think

**Comment by appernetic** [comment]
Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-01T10:55:24Z

**Comment by appernetic** [comment]
Is there some important settings needed in the config or in each md files front matter?

Also by default there is no assets folder in this theme when it's published, just /fonts and /modal

**Comment by appernetic** [comment]
There is no style_custom.css: 
error calling Get: stat /home/bror/Documents/JannesBlog/test/themes/hugo-bootstrap-premium/assets/css/style_custom.css: no such file or directory

So I created an empty file and got it working.

No need to have any extra settings in config or md files. But we have to add an empty style_custom.css in themes/hugo-bootstrap-premium/assets/css

**Comment by appernetic** [comment]
I have just added the missing file, updated theme.toml with the new features.

**Pull request merged**
