### PR TITLE
Mathjax support

### PR DESCRIPTION
**Pull request by dselivanov**
Hi. Thanks for great theme. Not sure if you are interested in this PR - it adds mathjax support. So feel free to decline.

### CODE REVIEW

**Comment by appernetic** [comment]
Hi, thanks!

Mathjax could be useful.

**Comment by appernetic** [comment]
Do you have any instructions on how to use it?

Maybe some helpful instructions that I could add to the README:

**Comment by dselivanov** [comment]
For inline math in markdown files wrap formulas with `$`. For example: `$a = /alpha X_i$`.
For "display style mathematics" wrap in double dollar `$$` and `<div>` tags: 
`<div>$$a = /alpha X_i$$</div>`. [Here is reference from hugo site](https://gohugo.io/tutorials/mathjax/).

**Comment by appernetic** [comment]
Ok, thanks!

I include a bit from here https://gohugo.io/tutorials/mathjax/ in the README and also added a class in the CSS.

**Comment by appernetic** [comment]
And moved the script from footer to script.html partials.

**Pull request merged**
