### PR TITLE
Add support for nested menus

### PR DESCRIPTION
**Pull request by kd7uiy**
The following code will allow for nested menus.

### CODE REVIEW

**Comment by appernetic** [comment]
Do you have instructions on how to use it?

**Comment by kd7uiy** [comment]
The instructions are the standard Hugo ones, having menus with a "Parent" defined. https://gohugo.io/content-management/menus/#nesting



```
    [[menu.main]]
    name = "Section folder"
    identifier = "sect"
    url = “/section/”

    [[menu.main]]
    name = "Sublevel one"
    identifier = "sub1"
    url = “/section/folder1/”

    [[menu.main]]
    name = "Sublevel two"
    identifier = "sub2"
    url = “/section/folder2/”
```

**Comment by gofford** [comment]
Hey @kd7uiy (cc: @appernetic) how would this PR be extended to support arbitrary depth nesting?

This is a great addition but as-is the nesting only seems to allow a single-depth nest, i.e., if I wanted to add another menu at `/section/folder1/mycontent` it will not render, even if I set the parent correctly.

**Comment by kd7uiy** [comment]
Will consider it, but I borrowed the code from somewhere else, just figured out how to connect it. I'll add it to my todo list, but that list is rather lengthy at the moment, so...

**Pull request merged**
